### ISSUE TITLE
enrol_paystack_charge_exception_handler" not found

### ISSUE THREAD

**Issue by fmanimashaun** [webong/plugin-moodle-enrol-paystack#8]
```
Exception - set_exception_handler(): Argument #1 ($callback) must be a valid callback or null, function "enrol_paystack_charge_exception_handler" not found or invalid function name
```

<img src="https://support.paystack.com/attachments/token/l9xtKbat2CtFtSEkzEcX02urM/?name=paystack+errors.png" alt="error msg">

**Comment by webong** [comment]
Hello @fmanimashaun ... please refer to this branch for the update moodle plugin https://github.com/PaystackHQ/plugin-moodle-enrol
